### ISSUE TITLE
Regner med det er her FKA skal putte inn det vi finner av "feil" i løsningen før KAT.

### ISSUE THREAD

**Issue by fkassl** [Felleskjopet/FKA---Plugins#1]

**Comment by mortenskau** [comment]
@WaqasSyed, svarer du på denne?

**Comment by WaqasSyed** [comment]
**Først;** Alle test scripts er i Test-xxx (CRM, SRM, Masterdata og Arkiv) spor så dette er ikke relevant. Alle issues som skal opprettes skal også ha vært i egen spor.

    Forklaring: Det er en kildekode område for 2 plugins. Vi har allerede dette i Masterdata kildekoden mappe med andre plugins, så det er et duplikat området og må slettes som snakket med @YerkoF og @youneshajji.

**Sekund;** Det er en del av migrasjon. Det er en funksjonalitet relatert med https://github.com/Felleskjopet/Test-Masterdata/issues/40.

**Comment by WaqasSyed** [comment]
For ny issue i overnevnte Test-xxx spor.
Bruk merkelapp:
1. Bug
2. Feil med Nivå
3. Area

**Comment by fkassl** [comment]
Jeg kan ikke se at knappen for oppretting av ny sak er aktivert jf opplæringsvideo for ny sak. Hverken Sveinung Slyngstad, Kari Mette Pettersen, Berit Ahlstrøm eller John Arild Leirnes (systemadministrator) har denne knappen i saksviewet, ( trykk Prewiev over for å se snapshot)
![opprette sak](https://cloud.githubusercontent.com/assets/22809093/22887572/e3632df4-f202-11e6-97af-7c745c6606ff.png)

**Comment by fkassl** [comment]
Saken overført til test-CRM
